<template>
  <div class="d-grid gap-2">
    <button
      :disabled="players.length < 3"
      @click="balanceTeams"
      class="btn btn-success btn-lg"
    >
      Balance
    </button>
  </div>
  <section v-if="balancedTeams?.length > 0">
    <h3>Team suggestions</h3>
    <section class="scrolling-wrapper row flex-nowrap mb-4" id="balancedTeams">
      <div v-for="suggestion in balancedTeams" class="pr-2 suggestion-card">
        <div class="card">
          <div class="card-body">
            <div class="row">
              <div class="col-6">
                <span class="badge bg-success rounded-pill float-start">{{
                  suggestion[0].value
                }}</span>
                <ul class="list-group list-group-flush">
                  <li
                    v-for="player in suggestion[0].players"
                    class="list-group-item"
                  >
                    {{ player.name }}
                  </li>
                </ul>
              </div>
              <div class="col-6">
                <span class="badge bg-success rounded-pill float-end">{{
                  suggestion[1].value
                }}</span>
                <ul class="list-group list-group-flush">
                  <li
                    v-for="player in suggestion[1].players"
                    class="list-group-item"
                  >
                    {{ player.name }}
                  </li>
                </ul>
              </div>
            </div>
            <div class="d-grid gap-2 mt-4">
              <button
                @click="shareTeams(suggestion)"
                class="btn btn-outline-success btn-sm float-end"
              >
                <i class="fa fa-share"></i>
                Condividi
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  </section>
</template>

<script setup lang="ts">
import type { Player } from "@/models/Player";
import { ref } from "vue";
import { balanceTeamsSuggestions } from "@/services/balancer.js";

const props = defineProps<{
  players: Player[];
}>();
const maxSuggestions = 5;

const balancedTeams = ref();
const balanceTeams = () => {
  balancedTeams.value = balanceTeamsSuggestions(props.players, maxSuggestions);
};

const shareTeams = (suggestion: any) => {
  const teamsText = {
    a: suggestion[0].players.map((p: Player) => p.name).join("\n"),
    b: suggestion[1].players.map((p: Player) => p.name).join("\n"),
  };
  const text = `
        Team A\n${teamsText.a}\n\nTeam B\n${teamsText.b}\n\nGenerated by: ${window.location.href}`;
  navigator.share({
    url: "", //TODO
    text: text,
  });
};
</script>

<style scoped></style>
